package abcmain;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
//import java.net.MalformedURLException;
//import java.net.URL;
import javax.swing.JFrame;

public class BuyCars extends javax.swing.JApplet {
    
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        getContentPane().setBackground(Color.PINK);
        this.setSize(450, 350);

        /* Create and display the applet */
        /*
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        */
        run();
    }

    public void run()
    {
        initComponents();
    }
 
    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Buy_New_Car = new javax.swing.JButton();
        Buy_Used_Car = new javax.swing.JButton();
        View = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 204));
        setPreferredSize(new java.awt.Dimension(500, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Buy_New_Car.setBackground(new java.awt.Color(255, 255, 255));
        Buy_New_Car.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        Buy_New_Car.setForeground(new java.awt.Color(102, 0, 102));
        Buy_New_Car.setText("Buy a New Car");
        Buy_New_Car.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Buy_New_Cars(evt);
            }
        });
        getContentPane().add(Buy_New_Car, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 130));

        Buy_Used_Car.setBackground(new java.awt.Color(255, 255, 255));
        Buy_Used_Car.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        Buy_Used_Car.setForeground(new java.awt.Color(102, 0, 102));
        Buy_Used_Car.setText("Buy a Used Car");
        Buy_Used_Car.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Buy_Used_Cars(evt);
            }
        });
        getContentPane().add(Buy_Used_Car, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 400, 120));

        View.setBackground(new java.awt.Color(255, 255, 255));
        View.setFont(new java.awt.Font("Gill Sans MT", 2, 14)); // NOI18N
        View.setForeground(new java.awt.Color(255, 0, 204));
        View.setText("View Models");
        View.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewModels(evt);
            }
        });
        getContentPane().add(View, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 260, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ViewModels(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewModels
        // TODO add your handling code here:
        
        //KAUMIL - I TRIED CALLING HTML PAGE FROM BUTTON ACTION BUT NO RESULTS
        //KAUMIL - IF YOU GOT NEWER METHODS, PLEASE HELP
        
        /*try {
            URL url = new URL("C:\\Users\\Gryffin\\Documents\\NetBeansProjects\\abc\\src\\abcmain\\ModelDisplay.html");
            getAppletContext().showDocument(url,"_blank");
        } catch (MalformedURLException ex) {
            showStatus("Not Found");
        }
        */
    }//GEN-LAST:event_ViewModels

    private void Buy_New_Cars(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buy_New_Cars
        try {
            // TODO add your handling code here:
            
            new TableNew_Cars();
            
            /*JFrame frame = new JFrame();
            BuyNewCars bnc = new BuyNewCars();
            frame.getContentPane().add(bnc);
            frame.setVisible(true);
            frame.setSize(450, 350);
            bnc.init();
            bnc.start();*/
        } catch (SQLException ex) {
            Logger.getLogger(BuyCars.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BuyCars.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Buy_New_Cars

    private void Buy_Used_Cars(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buy_Used_Cars
        try {
            // TODO add your handling code here:
            /*  JFrame frame = new JFrame();
            BuyUsedCars buc = new BuyUsedCars();
            frame.getContentPane().add(buc);
            frame.setVisible(true);
            frame.setSize(450, 350);
            buc.init();
            buc.start();
            */
            new TableUsed_Cars();
        } catch (SQLException ex) {
            Logger.getLogger(BuyCars.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BuyCars.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_Buy_Used_Cars


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton Buy_New_Car;
    protected javax.swing.JButton Buy_Used_Car;
    private javax.swing.JButton View;
    // End of variables declaration//GEN-END:variables
}
