package abcmain;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Registration extends javax.swing.JApplet {

    String user, pwd ;
    
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        getContentPane().setBackground(Color.BLUE);
        this.setSize(450, 350);

        /* Create and display the applet */
        /*try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        */
        run();
    }
    public void run() {
                    initComponents();
    }
    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SignUp = new javax.swing.JButton();
        Login = new javax.swing.JButton();
        NewUser = new javax.swing.JTextField();
        OldUser = new javax.swing.JTextField();
        Username = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        UsernameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 255));
        setMinimumSize(new java.awt.Dimension(500, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignUp.setText("SignUp");
        SignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpForm(evt);
            }
        });
        SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpActionPerformed(evt);
            }
        });
        getContentPane().add(SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        Login.setBackground(new java.awt.Color(255, 255, 255));
        Login.setText("Login");
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOGINMETHOD(evt);
            }
        });
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        NewUser.setBackground(new java.awt.Color(0, 0, 255));
        NewUser.setFont(new java.awt.Font("PMingLiU", 1, 18)); // NOI18N
        NewUser.setForeground(new java.awt.Color(255, 153, 153));
        NewUser.setText("New User? SignUp for Free");
        NewUser.setBorder(null);
        getContentPane().add(NewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 240, 30));

        OldUser.setBackground(new java.awt.Color(0, 0, 255));
        OldUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        OldUser.setForeground(new java.awt.Color(153, 255, 0));
        OldUser.setText("Already Registered? Login Here.");
        OldUser.setBorder(null);
        getContentPane().add(OldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        Username.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                CHECKUSER(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        getContentPane().add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 110, -1));
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 110, -1));

        UsernameLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        UsernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        UsernameLabel.setText("Username");
        getContentPane().add(UsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        PasswordLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel.setText("Password");
        getContentPane().add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpForm(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpForm
        // TODO add your handling code here:
            JFrame frame = new JFrame();
            SignUpForm newEntryData = new SignUpForm();
            frame.getContentPane().add(newEntryData);
            frame.setVisible(true);
            frame.setSize(550, 350);
            newEntryData.init();
            newEntryData.start();
    }//GEN-LAST:event_SignUpForm

    private void CHECKUSER(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_CHECKUSER
        // TODO add your handling code here:
        //KAUMIL - Verify Username from Database
    }//GEN-LAST:event_CHECKUSER

    private void LOGINMETHOD(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGINMETHOD
        // TODO add your handling code here:
        
        //KAUMIL - If both Username and password match then
        //Redirect to SellCar applet
        
        //SellCar applet launch code typed below
        
          /*JFrame frame = new JFrame();
            SellCar newSellCar = new SellCar();
            frame.getContentPane().add(newSellCar);
            frame.setVisible(true);
            frame.setSize(450, 350);
            newSellCar.init();
            newSellCar.start(); */
    }//GEN-LAST:event_LOGINMETHOD

    private void SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUpActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        user = Username.getText();
        char[] p  = Password.getPassword();
        pwd = new String(p);   
         if(user.equals("") || pwd.equals(""))
         {
              JOptionPane.showMessageDialog(this, "You cannot leave a field empty!");  
         }
         else
         {
            try {
                new Login(user,pwd);
            } catch (SQLException | ClassNotFoundException ex) {
              Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
    }//GEN-LAST:event_LoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JTextField NewUser;
    private javax.swing.JTextField OldUser;
    protected javax.swing.JPasswordField Password;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JButton SignUp;
    protected javax.swing.JTextField Username;
    private javax.swing.JLabel UsernameLabel;
    // End of variables declaration//GEN-END:variables

    
    
    
}
