
package abcmain;

import static abcmain.datasql.stmt;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class SellUsedCarForm extends javax.swing.JApplet {

    /**
     * Initializes the applet SellNewCarForm
     */
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellUsedCarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellUsedCarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellUsedCarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellUsedCarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        getContentPane().setBackground(Color.YELLOW);
        this.setSize(450, 350);
        //</editor-fold>

        /* Create and display the applet */
        /*try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }*/
        run();
    }
    public void run() {
                    initComponents();
                }
    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Company = new javax.swing.JLabel();
        Model = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        Contact = new javax.swing.JLabel();
        CompanyName = new javax.swing.JTextField();
        ModelName = new javax.swing.JTextField();
        PriceValue = new javax.swing.JTextField();
        ContactNumber = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SellerDetails = new javax.swing.JTextField();
        Seller = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Company.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Company.setForeground(new java.awt.Color(0, 0, 153));
        Company.setLabelFor(CompanyName);
        Company.setText("Company");
        getContentPane().add(Company, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        Model.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Model.setForeground(new java.awt.Color(0, 0, 153));
        Model.setLabelFor(ModelName);
        Model.setText("Model");
        getContentPane().add(Model, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        Price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Price.setForeground(new java.awt.Color(0, 0, 153));
        Price.setLabelFor(PriceValue);
        Price.setText("Price");
        getContentPane().add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        Contact.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Contact.setForeground(new java.awt.Color(0, 0, 153));
        Contact.setLabelFor(ContactNumber);
        Contact.setText("Contact");
        getContentPane().add(Contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));
        getContentPane().add(CompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 130, -1));
        getContentPane().add(ModelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 130, -1));
        getContentPane().add(PriceValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 130, -1));
        getContentPane().add(ContactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 130, -1));

        Submit.setText("Submit");
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Enter(evt);
            }
        });
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("Sell A Used Car");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));
        getContentPane().add(SellerDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 130, -1));

        Seller.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Seller.setForeground(new java.awt.Color(0, 0, 153));
        Seller.setLabelFor(SellerDetails);
        Seller.setText("Seller");
        getContentPane().add(Seller, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void Enter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Enter
        // TODO add your handling code here:
         if(ModelName.getText().equals("") || CompanyName.getText().equals("") || ContactNumber.getText().equals("") || PriceValue.getText().equals(""))
            {
             JOptionPane.showMessageDialog(this, "You cannot leave a field empty!");   
            }
       else 
       {
           String Model = ModelName.getText();
           String Company = CompanyName.getText();
           String Contact =ContactNumber.getText();
           String Price = PriceValue.getText();
           String seller = SellerDetails.getText();
           String  strsql ="Insert INTO usedcar(seller,company,model,price,contact)" + 
			 	" values('"+seller+"','"+Company+"','"+Model+"','"+Price+"','"+Contact+"')";
	// String strsql ="INSERT INTO usedcar(seller) values('car')" ;
           try {
               int rset = stmt.executeUpdate(strsql);
               JOptionPane.showMessageDialog(this, "Details of your car are successfully entered ! \n  Your deal is on the way!");   
               JFrame frame = new JFrame();
                        SellUsedCarForm newSellUsedCarForm = new SellUsedCarForm();
                        frame.getContentPane().add(newSellUsedCarForm);
                        frame.setVisible(true);
                        frame.setSize(450, 350);
                        newSellUsedCarForm.init();
                        newSellUsedCarForm.start();
           } catch (SQLException ex) {
               Logger.getLogger(SellNewCarForm.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
    }//GEN-LAST:event_Enter

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Company;
    protected javax.swing.JTextField CompanyName;
    private javax.swing.JLabel Contact;
    protected javax.swing.JTextField ContactNumber;
    private javax.swing.JLabel Model;
    protected javax.swing.JTextField ModelName;
    private javax.swing.JLabel Price;
    protected javax.swing.JTextField PriceValue;
    private javax.swing.JLabel Seller;
    protected javax.swing.JTextField SellerDetails;
    protected javax.swing.JButton Submit;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
